# Setup
title: "the missing semester of your cs education"

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled
timezone: America/Los_Angeles
domain: bkvbc.github.io
baseurl: "/dataclub/" # the subpath of your site, e.g. /blog
url: "https://bkvbc.github.io" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  "2020":
    output: true
# Excludes
# exclude:
#   - README.md
#   - Gemfile
#   - Gemfile.lock
#   - vendor
